name: Flutter

on:
  push:
    branches: [main, v*]
  pull_request:
    branches: [main, v*]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test latest stable, beta, dev, and main channels + last stable release
        # prior to the introduction of the unified `dart` developer tool.
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart

  test-dev:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test latest stable, beta, dev, and main channels + last stable release
        # prior to the introduction of the unified `dart` developer tool.
        sdk: [dev]
        version: ["2.1.0-12.1.pre"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}
          version: ${{ matrix.version }}

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version

      - name: Run hello world
        run: |
          echo "main() { print('hello world'); }" > hello.dart
          dart hello.dart

  test_pub:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Dart version
        run: dart --version
      - name: Flutter version
        run: flutter --version

      - name: Global activate + run
        run: |
          dart pub global activate stagehand
          mkdir testapp
          cd testapp
          stagehand console-simple
          dart pub get
          dart run
